name: Train ML and Commit Predictions

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run training
        run: |
          python ml/train.py
      - name: Commit predictions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ml_output/predictions.json ml_output/metrics.json
          git commit -m "Auto: update predictions" || echo "No changes to commit"
          git push
